/*
const mensagem = nota >= 6 ? 'Aprovado' : 'Reprovado';
*/
//Isso substitui o if e else

// Converter cada if/else para ternário:


// 1.

/*
let descricao;

if (temperatura > 30) {

  descricao = 'Quente';

} else {

  descricao = 'Agradável';

}
*/

const descriçao = temperatura > 30 ? 'Quente' : 'Agradavel';


// 2.

/*
let tipo;

if (numero % 2 === 0) {

  tipo = 'par';

} else {

  tipo = 'ímpar';

}
*/

const tipo = numero % 2 === 0 ? 'par' : 'impar';


// 3.

/*
let saudacao;

if (hora < 12) {

  saudacao = 'Bom dia';

} else {

  saudacao = 'Boa tarde/noite';

} 
*/

const saudacao = hora > 12 ? 'Bom dia' : 'Boa Tarde/Noite';

